<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="EntityConfigurations\**" />
    <Compile Remove="Migrations\**" />
    <Compile Remove="Seeds\**" />
    <EmbeddedResource Remove="EntityConfigurations\**" />
    <EmbeddedResource Remove="Migrations\**" />
    <EmbeddedResource Remove="Seeds\**" />
    <None Remove="EntityConfigurations\**" />
    <None Remove="Migrations\**" />
    <None Remove="Seeds\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.31" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DigiKala.Application\DigiKala.Application.csproj" />
    <ProjectReference Include="..\DigiKala.Infrastructure\DigiKala.Infrastructure.csproj" />
  </ItemGroup>

</Project>
